# Generated by Django 4.1.7 on 2023-03-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='missingPerson',
            fields=[
                ('missing_person_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('area', models.CharField(max_length=60)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='home/UserImages')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('mobile_no', models.CharField(max_length=13)),
                ('description', models.CharField(max_length=100)),
                ('user_role', models.CharField(max_length=100)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('last_seen', models.CharField(max_length=100)),
                ('police_station', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
