# Generated by Django 4.1.7 on 2023-03-21 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userfir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='image',
            field=models.ImageField(upload_to='userfir/missingPerson'),
        ),
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('fir_id', models.AutoField(primary_key=True, serialize=False)),
                ('police_station', models.CharField(max_length=100)),
                ('user_proof', models.ImageField(upload_to='userfir/firProof')),
                ('complaint_type', models.CharField(max_length=50)),
                ('against_whom', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
