# Generated by Django 4.1.7 on 2023-03-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfir', '0003_fir_timestamp_missingperson_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='criminl',
            fields=[
                ('criminal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=200)),
                ('contact_no', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=60)),
                ('area', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='criminal/missingPerson')),
                ('email', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
