# Generated by Django 4.1.7 on 2023-03-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userfir', '0004_criminl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='criminl',
            new_name='criminal',
        ),
    ]
