# Generated by Django 4.1.7 on 2023-03-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
