# Generated by Django 4.1.7 on 2023-03-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser_division_customuser_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=10)),
                ('msg', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
